import java.awt.*;
import javax.swing.*;
import java.util.*;
import java.util.Locale;
import java.text.*;
/**
 *
 * @author lawre
 */
public class app_ui extends JFrame {

    JFrame frame = new JFrame();
    OrderInfo order = new OrderInfo();
    /**
     * Creates new form app_ui
     */
    public app_ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Main_Menu = new javax.swing.JPanel();
        mainMenuPanel1 = new javax.swing.JPanel();
        smallScaleBtn = new javax.swing.JButton();
        wedBtn = new javax.swing.JButton();
        CorpoBtn = new javax.swing.JButton();
        mainLabel1 = new javax.swing.JLabel();
        mainExitBtn = new javax.swing.JButton();
        EventInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ok_eventInfoBtn = new javax.swing.JButton();
        cancel_eventInfoBtn = new javax.swing.JButton();
        eventInfoPanel1 = new javax.swing.JPanel();
        EvDateLabel = new javax.swing.JLabel();
        NoAttendLabel = new javax.swing.JLabel();
        noAttendField = new javax.swing.JTextField();
        evDateField = new javax.swing.JTextField();
        Menu_Picker = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        western_label = new javax.swing.JLabel();
        westScrollPane = new javax.swing.JScrollPane();
        westernTxtArea = new javax.swing.JTextArea();
        WestSelectBtn = new javax.swing.JButton();
        westPriceLabel = new javax.swing.JLabel();
        phPanel = new javax.swing.JPanel();
        phScrollPane = new javax.swing.JScrollPane();
        phTxtArea = new javax.swing.JTextArea();
        Filipino_label = new javax.swing.JLabel();
        PhSelectBtn1 = new javax.swing.JButton();
        phPriceLabel = new javax.swing.JLabel();
        medPanel = new javax.swing.JPanel();
        medScrollPane1 = new javax.swing.JScrollPane();
        medTxtArea1 = new javax.swing.JTextArea();
        Med_Label = new javax.swing.JLabel();
        PhSelectBtn2 = new javax.swing.JButton();
        medPriceLabel = new javax.swing.JLabel();
        Payment = new javax.swing.JPanel();
        paymentLabel = new javax.swing.JLabel();
        payOptionPanel = new javax.swing.JPanel();
        payOptionsPanel = new javax.swing.JPanel();
        payOptionField = new javax.swing.JLabel();
        cashSelect = new javax.swing.JButton();
        creditSelect = new javax.swing.JButton();
        creditPanel = new javax.swing.JPanel();
        ccInfoLabel = new javax.swing.JLabel();
        ccInternalPanel1 = new javax.swing.JPanel();
        ccLastNamelabel = new javax.swing.JLabel();
        ccNumberTxtField = new javax.swing.JTextField();
        ccCusLnameField = new javax.swing.JTextField();
        ccNameLabel = new javax.swing.JLabel();
        ccNumberLabel = new javax.swing.JLabel();
        ccCusFnameField = new javax.swing.JTextField();
        ccInternalPanel2 = new javax.swing.JPanel();
        ccBackButton1 = new javax.swing.JButton();
        ccOkButton = new javax.swing.JButton();
        cashPanel = new javax.swing.JPanel();
        cashInternalPanel1 = new javax.swing.JPanel();
        cashLastNameLabel = new javax.swing.JLabel();
        cashCusLnameField1 = new javax.swing.JTextField();
        cashNameLabel1 = new javax.swing.JLabel();
        cashCusFnameField1 = new javax.swing.JTextField();
        cashInfoLabel1 = new javax.swing.JLabel();
        cashInternalPanel2 = new javax.swing.JPanel();
        cashBackButton = new javax.swing.JButton();
        cashOkButton = new javax.swing.JButton();
        paymentPanel1 = new javax.swing.JPanel();
        paxLabel = new javax.swing.JLabel();
        perHeadLabel = new javax.swing.JLabel();
        invoiceLabel = new javax.swing.JLabel();
        ppHeadTextField = new javax.swing.JTextField();
        paxTextField1 = new javax.swing.JTextField();
        subtotalLabel = new javax.swing.JLabel();
        subtotalTextField1 = new javax.swing.JTextField();
        paymentBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AA Catering App");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        Main_Menu.setBackground(new java.awt.Color(255, 255, 255));

        mainMenuPanel1.setBackground(new java.awt.Color(255, 255, 255));

        smallScaleBtn.setText("Small-Scale");
        smallScaleBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        smallScaleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smallScaleBtnMouseClicked(evt);
            }
        });

        wedBtn.setText("Weddings/Occasions");
        wedBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        wedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wedBtnActionPerformed(evt);
            }
        });

        CorpoBtn.setText("Corporate Events");
        CorpoBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CorpoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorpoBtnActionPerformed(evt);
            }
        });

        mainLabel1.setText("Welcome to AA Catering!");
        mainLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        mainExitBtn.setText("Exit");
        mainExitBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPanel1Layout = new javax.swing.GroupLayout(mainMenuPanel1);
        mainMenuPanel1.setLayout(mainMenuPanel1Layout);
        mainMenuPanel1Layout.setHorizontalGroup(
            mainMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanel1Layout.createSequentialGroup()
                        .addGroup(mainMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainExitBtn)
                            .addComponent(CorpoBtn)
                            .addComponent(wedBtn)
                            .addComponent(smallScaleBtn))
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );

        mainMenuPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CorpoBtn, mainExitBtn, smallScaleBtn, wedBtn});

        mainMenuPanel1Layout.setVerticalGroup(
            mainMenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel1)
                .addGap(18, 18, 18)
                .addComponent(smallScaleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wedBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorpoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainExitBtn)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Main_MenuLayout = new javax.swing.GroupLayout(Main_Menu);
        Main_Menu.setLayout(Main_MenuLayout);
        Main_MenuLayout.setHorizontalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(mainMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        Main_MenuLayout.setVerticalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(mainMenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel2.add(Main_Menu, "main_menu");

        EventInfo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Enter event info below");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ok_eventInfoBtn.setText("Okay");
        ok_eventInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_eventInfoBtnMouseClicked(evt);
            }
        });
        ok_eventInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_eventInfoBtnActionPerformed(evt);
            }
        });

        cancel_eventInfoBtn.setText("Cancel");
        cancel_eventInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_eventInfoBtnMouseClicked(evt);
            }
        });

        eventInfoPanel1.setBackground(new java.awt.Color(255, 255, 255));

        EvDateLabel.setText("Date of Event: ");
        EvDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        NoAttendLabel.setText("Number of attendees:");
        NoAttendLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        noAttendField.setColumns(25);

        evDateField.setColumns(15);

        javax.swing.GroupLayout eventInfoPanel1Layout = new javax.swing.GroupLayout(eventInfoPanel1);
        eventInfoPanel1.setLayout(eventInfoPanel1Layout);
        eventInfoPanel1Layout.setHorizontalGroup(
            eventInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventInfoPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NoAttendLabel)
                    .addComponent(EvDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eventInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noAttendField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evDateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        eventInfoPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EvDateLabel, NoAttendLabel});

        eventInfoPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {evDateField, noAttendField});

        eventInfoPanel1Layout.setVerticalGroup(
            eventInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventInfoPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoAttendLabel)
                    .addComponent(noAttendField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(eventInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EvDateLabel)
                    .addComponent(evDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EventInfoLayout = new javax.swing.GroupLayout(EventInfo);
        EventInfo.setLayout(EventInfoLayout);
        EventInfoLayout.setHorizontalGroup(
            EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(EventInfoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(ok_eventInfoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel_eventInfoBtn))
                    .addComponent(eventInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(742, Short.MAX_VALUE))
        );

        EventInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancel_eventInfoBtn, ok_eventInfoBtn});

        EventInfoLayout.setVerticalGroup(
            EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_eventInfoBtn)
                    .addComponent(cancel_eventInfoBtn))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        jPanel2.add(EventInfo, "EventPanel");

        Menu_Picker.setBackground(new java.awt.Color(255, 255, 255));
        Menu_Picker.setLayout(new java.awt.GridLayout(1, 0));

        westPanel.setBackground(new java.awt.Color(255, 255, 255));

        western_label.setText("Western Menu");
        western_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        westernTxtArea.setEditable(false);
        westernTxtArea.setColumns(20);
        westernTxtArea.setRows(5);
        westernTxtArea.setText("Appetizers\nHand-cut Fries\nCheese ball\n\nEntrees\nBeef Steak \nDuck Breast Steak\nPumpkin and Pork Croquette\nShrimp tempura and Spicy Sauce\n\nDesserts\nTropical Fruits\nIce cream");
        westScrollPane.setViewportView(westernTxtArea);

        WestSelectBtn.setText("Select");
        WestSelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WestSelectBtnActionPerformed(evt);
            }
        });

        westPriceLabel.setText("PHP 550.00 per head");

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(western_label)
                    .addComponent(westScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WestSelectBtn)
                    .addComponent(westPriceLabel))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(western_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(westScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(westPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WestSelectBtn)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        Menu_Picker.add(westPanel);

        phPanel.setBackground(new java.awt.Color(255, 255, 255));

        phTxtArea.setEditable(false);
        phTxtArea.setColumns(20);
        phTxtArea.setRows(5);
        phTxtArea.setText("Appetizers\nTinapa Rolls\nBaked Scallops\n\nEntrees\nPork Sisig\nChicken Binakol\nBeef Ribs Nilaga\nBicol Express\n\nDesserts\nHalo-halo\nMaja Blanca");
        phScrollPane.setViewportView(phTxtArea);

        Filipino_label.setText("Filipino Menu");
        Filipino_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        PhSelectBtn1.setText("Select");
        PhSelectBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhSelectBtn1ActionPerformed(evt);
            }
        });

        phPriceLabel.setText("PHP 525.00 per head");

        javax.swing.GroupLayout phPanelLayout = new javax.swing.GroupLayout(phPanel);
        phPanel.setLayout(phPanelLayout);
        phPanelLayout.setHorizontalGroup(
            phPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(phPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Filipino_label)
                    .addComponent(phScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhSelectBtn1)
                    .addComponent(phPriceLabel))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        phPanelLayout.setVerticalGroup(
            phPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Filipino_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhSelectBtn1)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        Menu_Picker.add(phPanel);

        medPanel.setBackground(new java.awt.Color(255, 255, 255));

        medTxtArea1.setEditable(false);
        medTxtArea1.setColumns(20);
        medTxtArea1.setRows(5);
        medTxtArea1.setText("Appetizers\nHummus\nSafiha\n\nEntrees\nShish Kabob\nLamb Kabob\nVeggie Kbob\nShrimp with Vegetables\n\nDesserts\nSyrian Rice Pudding\nBaklava");
        medScrollPane1.setViewportView(medTxtArea1);

        Med_Label.setText("Mediterranean Menu");
        Med_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        PhSelectBtn2.setText("Select");
        PhSelectBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhSelectBtn2ActionPerformed(evt);
            }
        });

        medPriceLabel.setText("PHP 575.00 per head");

        javax.swing.GroupLayout medPanelLayout = new javax.swing.GroupLayout(medPanel);
        medPanel.setLayout(medPanelLayout);
        medPanelLayout.setHorizontalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Med_Label)
                    .addComponent(medScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhSelectBtn2)
                    .addComponent(medPriceLabel))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        medPanelLayout.setVerticalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Med_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhSelectBtn2)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        Menu_Picker.add(medPanel);

        jPanel2.add(Menu_Picker, "menuPanel");

        paymentLabel.setText("Payment");
        paymentLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        payOptionPanel.setBackground(new java.awt.Color(255, 255, 255));
        payOptionPanel.setLayout(new java.awt.CardLayout());

        payOptionField.setText("Select a payment option:");
        payOptionField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cashSelect.setText("Cash");
        cashSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashSelectActionPerformed(evt);
            }
        });

        creditSelect.setText("Credit");
        creditSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout payOptionsPanelLayout = new javax.swing.GroupLayout(payOptionsPanel);
        payOptionsPanel.setLayout(payOptionsPanelLayout);
        payOptionsPanelLayout.setHorizontalGroup(
            payOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(payOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cashSelect)
                        .addComponent(creditSelect))
                    .addComponent(payOptionField))
                .addContainerGap(539, Short.MAX_VALUE))
        );

        payOptionsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cashSelect, creditSelect});

        payOptionsPanelLayout.setVerticalGroup(
            payOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payOptionField)
                .addGap(27, 27, 27)
                .addComponent(cashSelect)
                .addGap(18, 18, 18)
                .addComponent(creditSelect)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        payOptionPanel.add(payOptionsPanel, "payOptionPanel");

        ccInfoLabel.setText("Enter your credit card info here");
        ccInfoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ccLastNamelabel.setText("Customer Last Name:");

        ccNumberTxtField.setColumns(20);
        ccNumberTxtField.setText(" ");

        ccCusLnameField.setColumns(20);

        ccNameLabel.setText("Customer First Name:");

        ccNumberLabel.setText("Card Number: ");

        ccCusFnameField.setColumns(20);

        javax.swing.GroupLayout ccInternalPanel1Layout = new javax.swing.GroupLayout(ccInternalPanel1);
        ccInternalPanel1.setLayout(ccInternalPanel1Layout);
        ccInternalPanel1Layout.setHorizontalGroup(
            ccInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccInternalPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ccInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ccInternalPanel1Layout.createSequentialGroup()
                        .addComponent(ccNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ccCusFnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addGroup(ccInternalPanel1Layout.createSequentialGroup()
                        .addComponent(ccNumberLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ccNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(ccInternalPanel1Layout.createSequentialGroup()
                        .addComponent(ccLastNamelabel)
                        .addGap(18, 18, 18)
                        .addComponent(ccCusLnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ccInternalPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ccLastNamelabel, ccNameLabel, ccNumberLabel});

        ccInternalPanel1Layout.setVerticalGroup(
            ccInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccInternalPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ccInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccNameLabel)
                    .addComponent(ccCusFnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ccInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccLastNamelabel)
                    .addComponent(ccCusLnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ccInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccNumberLabel)
                    .addComponent(ccNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ccBackButton1.setText("BACK");
        ccBackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccBackButton1ActionPerformed(evt);
            }
        });

        ccOkButton.setText("OK");

        javax.swing.GroupLayout ccInternalPanel2Layout = new javax.swing.GroupLayout(ccInternalPanel2);
        ccInternalPanel2.setLayout(ccInternalPanel2Layout);
        ccInternalPanel2Layout.setHorizontalGroup(
            ccInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccInternalPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ccOkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccBackButton1)
                .addContainerGap())
        );

        ccInternalPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ccBackButton1, ccOkButton});

        ccInternalPanel2Layout.setVerticalGroup(
            ccInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccInternalPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ccInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccOkButton)
                    .addComponent(ccBackButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout creditPanelLayout = new javax.swing.GroupLayout(creditPanel);
        creditPanel.setLayout(creditPanelLayout);
        creditPanelLayout.setHorizontalGroup(
            creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccInfoLabel)
                    .addComponent(ccInternalPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccInternalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        creditPanelLayout.setVerticalGroup(
            creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ccInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccInternalPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccInternalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        payOptionPanel.add(creditPanel, "creditPanel");

        cashLastNameLabel.setText("Customer Last Name:");

        cashCusLnameField1.setColumns(40);

        cashNameLabel1.setText("Customer First Name:");

        cashCusFnameField1.setColumns(40);

        javax.swing.GroupLayout cashInternalPanel1Layout = new javax.swing.GroupLayout(cashInternalPanel1);
        cashInternalPanel1.setLayout(cashInternalPanel1Layout);
        cashInternalPanel1Layout.setHorizontalGroup(
            cashInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashInternalPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashNameLabel1)
                    .addComponent(cashLastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(cashInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashCusFnameField1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(cashCusLnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap())
        );

        cashInternalPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cashLastNameLabel, cashNameLabel1});

        cashInternalPanel1Layout.setVerticalGroup(
            cashInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashInternalPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashNameLabel1)
                    .addComponent(cashCusFnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cashInternalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashLastNameLabel)
                    .addComponent(cashCusLnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cashInfoLabel1.setText("Enter your customer info here:");
        cashInfoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cashBackButton.setText("BACK");
        cashBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashBackButtonActionPerformed(evt);
            }
        });

        cashOkButton.setText("OK");

        javax.swing.GroupLayout cashInternalPanel2Layout = new javax.swing.GroupLayout(cashInternalPanel2);
        cashInternalPanel2.setLayout(cashInternalPanel2Layout);
        cashInternalPanel2Layout.setHorizontalGroup(
            cashInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashInternalPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashOkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashBackButton)
                .addContainerGap())
        );
        cashInternalPanel2Layout.setVerticalGroup(
            cashInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashInternalPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashOkButton)
                    .addComponent(cashBackButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout cashPanelLayout = new javax.swing.GroupLayout(cashPanel);
        cashPanel.setLayout(cashPanelLayout);
        cashPanelLayout.setHorizontalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashInfoLabel1)
                    .addComponent(cashInternalPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashInternalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        cashPanelLayout.setVerticalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashInfoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashInternalPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashInternalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        payOptionPanel.add(cashPanel, "cashPanel");

        paxLabel.setText("Pax");

        perHeadLabel.setText("price per head");

        invoiceLabel.setText("Invoice");
        invoiceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ppHeadTextField.setColumns(15);
        ppHeadTextField.setEditable(false);
        ppHeadTextField.setText(" ");
        ppHeadTextField.setToolTipText("");

        paxTextField1.setColumns(15);
        paxTextField1.setEditable(false);
        paxTextField1.setText(" ");
        paxTextField1.setToolTipText("");

        subtotalLabel.setText("subtotal");

        subtotalTextField1.setColumns(15);
        subtotalTextField1.setEditable(false);
        subtotalTextField1.setText(" ");
        subtotalTextField1.setToolTipText("");

        javax.swing.GroupLayout paymentPanel1Layout = new javax.swing.GroupLayout(paymentPanel1);
        paymentPanel1.setLayout(paymentPanel1Layout);
        paymentPanel1Layout.setHorizontalGroup(
            paymentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentPanel1Layout.createSequentialGroup()
                        .addGroup(paymentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paxLabel)
                            .addComponent(perHeadLabel)
                            .addComponent(subtotalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(paymentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(paxTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppHeadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotalTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(invoiceLabel))
                .addContainerGap())
        );

        paymentPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {paxLabel, perHeadLabel, subtotalLabel});

        paymentPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {paxTextField1, ppHeadTextField, subtotalTextField1});

        paymentPanel1Layout.setVerticalGroup(
            paymentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoiceLabel)
                .addGap(18, 18, 18)
                .addGroup(paymentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(paymentPanel1Layout.createSequentialGroup()
                        .addComponent(paxTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ppHeadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subtotalTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paymentPanel1Layout.createSequentialGroup()
                        .addComponent(paxLabel)
                        .addGap(21, 21, 21)
                        .addComponent(perHeadLabel)
                        .addGap(27, 27, 27)
                        .addComponent(subtotalLabel)))
                .addContainerGap())
        );

        paymentBackBtn.setText("Back");
        paymentBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaymentLayout = new javax.swing.GroupLayout(Payment);
        Payment.setLayout(PaymentLayout);
        PaymentLayout.setHorizontalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentLayout.createSequentialGroup()
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(paymentLabel))
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paymentPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentBackBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PaymentLayout.setVerticalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paymentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentBackBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(payOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Payment, "payPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void cancel_eventInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        CardLayout card = (CardLayout)jPanel2.getLayout();
        card.show(jPanel2, "main_menu");
    }                                                

    private void ok_eventInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {                                             
        String PaxInput = noAttendField.getText();
        JOptionPane.showMessageDialog(frame, "Number of Attendees: "+PaxInput,"AA Catering App",JOptionPane.INFORMATION_MESSAGE);
        
        order.setPax(PaxInput);
        paxTextField1.setText(order.getPax());

        String DateInput = evDateField.getText();
        order.setDate(DateInput);
        
        CardLayout card = (CardLayout)jPanel2.getLayout();
        card.show(jPanel2, "menuPanel");
                
    }                                            

    private void WestSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
        CardLayout card = (CardLayout)jPanel2.getLayout();
        
        //Currency Php = Currency.getInstance("PHP");
        //Locale Ph= new Locale("ph", "PHP");
        //NumberFormat Phpformat= NumberFormat.getInstance(new Locale("ph","PH"));
        
        order.setWestPrice("550");
        ppHeadTextField.setText(NumberFormat.getCurrencyInstance(new Locale("en","PH")).format(Double.parseDouble(order.getWestPrice())));
        
        Double nPax = Double.parseDouble(order.getPax());
        Double WestSubTotal = 550 * nPax;
        
        order.setWestSubTotal(String.valueOf(WestSubTotal));
        subtotalTextField1.setText(NumberFormat.getCurrencyInstance(new Locale("en","PH")).format(Double.parseDouble(order.getWestSubTotal())));
        
        card.show(jPanel2, "payPanel");

    }                                             

    private void PhSelectBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        CardLayout card = (CardLayout)jPanel2.getLayout();
        
        order.setFilPrice("525");
        ppHeadTextField.setText(NumberFormat.getCurrencyInstance(new Locale("en","PH")).format(Double.parseDouble(order.getFilPrice())));
        
        Double nPax = Double.parseDouble(order.getPax());
        Double FilSubTotal = 525 * nPax;
        
        order.setFilSubTotal(String.valueOf(FilSubTotal));
        subtotalTextField1.setText(NumberFormat.getCurrencyInstance(new Locale("en","PH")).format(Double.parseDouble(order.getFilSubTotal())));
        
        card.show(jPanel2, "payPanel");
    }                                            

    private void PhSelectBtn2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        CardLayout card = (CardLayout)jPanel2.getLayout();
        
        order.setMedPrice("575");
        ppHeadTextField.setText(NumberFormat.getCurrencyInstance(new Locale("en","PH")).format(Double.parseDouble(order.getMedPrice())));
        
        Double nPax = Double.parseDouble(order.getPax());
        Double MedSubTotal = 575 * nPax;
        
        order.setMedSubTotal(String.valueOf(MedSubTotal));
        subtotalTextField1.setText(NumberFormat.getCurrencyInstance(new Locale("en","PH")).format(Double.parseDouble(order.getMedSubTotal())));
        
        card.show(jPanel2, "payPanel");
    }                                            

    private void smallScaleBtnMouseClicked(java.awt.event.MouseEvent evt) {                                           
        CardLayout card = (CardLayout)jPanel2.getLayout();
        
        order.setEventType("Small-Scale");
        
        card.show(jPanel2, "EventPanel");
    }                                          

    private void wedBtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        CardLayout card = (CardLayout)jPanel2.getLayout();
        
        order.setEventType("Wedding/Occasion");
        
        card.show(jPanel2, "EventPanel");
    }                                      

    private void CorpoBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CardLayout card = (CardLayout)jPanel2.getLayout();
        
        order.setEventType("Corporate Event");
        
        card.show(jPanel2, "EventPanel");
    }                                        

    private void mainExitBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        JOptionPane.showMessageDialog(frame, "Exiting Program");
        System.exit(0);
    }                                           

    private void creditSelectActionPerformed(java.awt.event.ActionEvent evt) {                                             
        CardLayout card = (CardLayout)payOptionPanel.getLayout();
        card.show(payOptionPanel, "creditPanel");
    }                                            

    private void cashSelectActionPerformed(java.awt.event.ActionEvent evt) {                                           
        CardLayout card = (CardLayout)payOptionPanel.getLayout();
        card.show(payOptionPanel, "cashPanel");
    }                                          

    private void paymentBackBtnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        CardLayout card = (CardLayout)jPanel2.getLayout();
        CardLayout card2 = (CardLayout)payOptionPanel.getLayout();
        card.show(jPanel2, "menuPanel");
        card2.show(payOptionPanel, "payOptionPanel");
    }                                              

    private void ccBackButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        CardLayout card = (CardLayout)payOptionPanel.getLayout();
        card.show(payOptionPanel, "payOptionPanel");
    }                                             

    private void cashBackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        CardLayout card = (CardLayout)payOptionPanel.getLayout();
        card.show(payOptionPanel, "payOptionPanel");
    }                                              

    private void ok_eventInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app_ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CorpoBtn;
    private javax.swing.JLabel EvDateLabel;
    private javax.swing.JPanel EventInfo;
    private javax.swing.JLabel Filipino_label;
    private javax.swing.JPanel Main_Menu;
    private javax.swing.JLabel Med_Label;
    private javax.swing.JPanel Menu_Picker;
    private javax.swing.JLabel NoAttendLabel;
    private javax.swing.JPanel Payment;
    private javax.swing.JButton PhSelectBtn1;
    private javax.swing.JButton PhSelectBtn2;
    private javax.swing.JButton WestSelectBtn;
    private javax.swing.JButton cancel_eventInfoBtn;
    private javax.swing.JButton cashBackButton;
    private javax.swing.JTextField cashCusFnameField1;
    private javax.swing.JTextField cashCusLnameField1;
    private javax.swing.JLabel cashInfoLabel1;
    private javax.swing.JPanel cashInternalPanel1;
    private javax.swing.JPanel cashInternalPanel2;
    private javax.swing.JLabel cashLastNameLabel;
    private javax.swing.JLabel cashNameLabel1;
    private javax.swing.JButton cashOkButton;
    private javax.swing.JPanel cashPanel;
    private javax.swing.JButton cashSelect;
    private javax.swing.JButton ccBackButton1;
    private javax.swing.JTextField ccCusFnameField;
    private javax.swing.JTextField ccCusLnameField;
    private javax.swing.JLabel ccInfoLabel;
    private javax.swing.JPanel ccInternalPanel1;
    private javax.swing.JPanel ccInternalPanel2;
    private javax.swing.JLabel ccLastNamelabel;
    private javax.swing.JLabel ccNameLabel;
    private javax.swing.JLabel ccNumberLabel;
    private javax.swing.JTextField ccNumberTxtField;
    private javax.swing.JButton ccOkButton;
    private javax.swing.JPanel creditPanel;
    private javax.swing.JButton creditSelect;
    private javax.swing.JTextField evDateField;
    private javax.swing.JPanel eventInfoPanel1;
    private javax.swing.JLabel invoiceLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mainExitBtn;
    private javax.swing.JLabel mainLabel1;
    private javax.swing.JPanel mainMenuPanel1;
    private javax.swing.JPanel medPanel;
    private javax.swing.JLabel medPriceLabel;
    private javax.swing.JScrollPane medScrollPane1;
    private javax.swing.JTextArea medTxtArea1;
    private javax.swing.JTextField noAttendField;
    public javax.swing.JButton ok_eventInfoBtn;
    private javax.swing.JLabel paxLabel;
    private javax.swing.JTextField paxTextField1;
    private javax.swing.JLabel payOptionField;
    private javax.swing.JPanel payOptionPanel;
    private javax.swing.JPanel payOptionsPanel;
    private javax.swing.JButton paymentBackBtn;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JPanel paymentPanel1;
    private javax.swing.JLabel perHeadLabel;
    private javax.swing.JPanel phPanel;
    private javax.swing.JLabel phPriceLabel;
    private javax.swing.JScrollPane phScrollPane;
    private javax.swing.JTextArea phTxtArea;
    private javax.swing.JTextField ppHeadTextField;
    private javax.swing.JButton smallScaleBtn;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JTextField subtotalTextField1;
    private javax.swing.JButton wedBtn;
    private javax.swing.JPanel westPanel;
    private javax.swing.JLabel westPriceLabel;
    private javax.swing.JScrollPane westScrollPane;
    private javax.swing.JTextArea westernTxtArea;
    private javax.swing.JLabel western_label;
    // End of variables declaration                   
}